export enum ChannelEnum {
  LOG_IN = "LOG_IN",
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  SAVE_CREDENTIAL = "SAVE_CREDENTIAL",
  GET_ALL_CREDENTIALS = "GET_ALL_CREDENTIALS",
  IS_NEW_USER = "IS_NEW_USER",
}
